### ISSUE TITLE
Connection failure

### ISSUE THREAD

**Issue by adheesh24** [arissa34/Android-Multi-Bluetooth-Library#12]
Hi,
When I try to run the application having 1 client, I am able to detect the device and pair it with the server successfully but getting an error on the client side, "Client connexion error" and it goes in an endless loop. 
And when I try to debug I get the below error.

09-27 16:57:25.413 8000-8121/com.ramimartin.sample.multibluetooth W/BluetoothAdapter: getBluetoothService() called with no BluetoothManagerCallback
09-27 16:57:25.424 21958-22043/? W/bt-rfcomm: rfc_port_closed
09-27 16:57:25.425 21958-22065/? W/bt-btif: invalid rfc slot id: 6986
09-27 16:57:25.434 8000-8121/com.ramimartin.sample.multibluetooth W/BT: Fallback failed. Cancelling.
                                                                        java.io.IOException: read failed, socket might closed or timeout, read ret: -1
                                                                            at android.bluetooth.BluetoothSocket.readAll(BluetoothSocket.java:517)
                                                                            at android.bluetooth.BluetoothSocket.waitSocketSignal(BluetoothSocket.java:494)
                                                                            at android.bluetooth.BluetoothSocket.connect(BluetoothSocket.java:324)
                                                                            at com.ramimartin.multibluetooth.bluetooth.client.BluetoothConnector$FallbackBluetoothSocket.connect(BluetoothConnector.java:206)
                                                                            at com.ramimartin.multibluetooth.bluetooth.client.BluetoothConnector.connect(BluetoothConnector.java:60)
                                                                            at com.ramimartin.multibluetooth.bluetooth.client.BluetoothClient.run(BluetoothClient.java:54)
                                                                            at java.lang.Thread.run(Thread.java:818)

```
                                                                    [ 09-27 16:57:25.434  8000: 8121 E/         ]
                                                                    ===> mSocket IOException
                                                                    java.io.IOException: ===> Could not connect to device: 08:62:66:67:70:24
                                                                        at com.ramimartin.multibluetooth.bluetooth.client.BluetoothConnector.connect(BluetoothConnector.java:75)
                                                                        at com.ramimartin.multibluetooth.bluetooth.client.BluetoothClient.run(BluetoothClient.java:54)
                                                                        at java.lang.Thread.run(Thread.java:818)
```

Can anyone help me out with this??

Thanks.

**Comment by adheesh24** [comment]
My bad I wasn't creating a thread from the server side to the client. So was getting this issue.
